/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.HistorialPrecio;
import ar.com.ventas.entities.Producto;
import ar.com.ventas.entities.Proveedor;
import ar.com.ventas.entities.Rubro;
import ar.com.ventas.entities.SubRubro;
import ar.com.ventas.services.HistorialPrecioService;
import ar.com.ventas.services.ProductoService;
import ar.com.ventas.services.ProveedorService;
import ar.com.ventas.services.RubroService;
import ar.com.ventas.services.SubRubroService;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcela
 */
public class ModificarProductoFrame1 extends javax.swing.JFrame {

    private List<Rubro> listaRubros = new ArrayList<Rubro>();
    private List<SubRubro> listaSubRubros = new ArrayList<SubRubro>();
    private List<Proveedor> proveedores;
    private List<HistorialPrecio> precios;
    private String filtro;
    private Producto productoRelacionado = null;
    private Producto producto;
    private List<Producto> productosRelacionados = null;
    private DecimalFormat df = new DecimalFormat("#0.00");
    private DecimalFormat df1 = new DecimalFormat("#0.0");
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form NuevoProductoFrame
     */
    public ModificarProductoFrame1(Producto producto, String filtro) {
        getContentPane().setBackground(new java.awt.Color(245, 222, 179));
        this.initComponents();
        this.filtro = filtro;
        this.producto = producto;
        this.borrarCampos();
        this.llenarComboRubro();
        this.llenarComboSubRubro();
        llenarCampos();
        idTxt.setEditable(false);
        nombreTxt.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        guardarBtn = new javax.swing.JButton();
        volerBtn = new javax.swing.JButton();
        codigoBarrasTxt = new javax.swing.JTextField();
        impuestoTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        sugeridoTxt = new javax.swing.JTextField();
        precioTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboRubro = new javax.swing.JComboBox();
        comboSubRubro = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        unidadChk = new javax.swing.JCheckBox();
        cantidadCajaTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        codigoRelacionTxt = new javax.swing.JTextField();
        filtroTxt = new javax.swing.JTextField();
        comboCaja = new javax.swing.JComboBox<>();
        buscarPorCodigoBtn = new javax.swing.JButton();
        buscarPorFiltroBtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        costoSinIvaTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        margenTxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        costoConIvaTxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cantidadPorBultoTxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        descuentoTxt = new javax.swing.JTextField();
        precioCalculadoTxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        sugeridoCalculadoTxt = new javax.swing.JTextField();
        calcularBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        comboI = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        ultimaFechaTxt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        margenClienteTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nombreProveBuscarTxt = new javax.swing.JTextField();
        comboProv = new javax.swing.JComboBox<>();
        agregaProveedorBtn = new javax.swing.JButton();
        idTxt = new javax.swing.JTextField();
        inactivoChk = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MODIFICAR PRODUCTO V.2");

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        volerBtn.setText("Volver");
        volerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volerBtnActionPerformed(evt);
            }
        });

        codigoBarrasTxt.setText("Codigo de Barras");
        codigoBarrasTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoBarrasTxtActionPerformed(evt);
            }
        });

        impuestoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        impuestoTxt.setText("Impuesto");

        nombreTxt.setText("DETALLE");
        nombreTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreTxtKeyPressed(evt);
            }
        });

        sugeridoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sugeridoTxt.setText("Sugerido");

        precioTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precioTxt.setText("Precio");
        precioTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                precioTxtKeyPressed(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel4.setText("Impuesto");

        jLabel5.setText("Detalle:");

        jLabel6.setText("Precio Venta");

        jLabel7.setText("Sugerido");

        jLabel9.setText("Rubro:");

        jLabel10.setText("Sub Rubro:");

        comboRubro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRubroActionPerformed(evt);
            }
        });

        comboSubRubro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Código de Barras:");

        jLabel8.setText("*");

        jLabel11.setText("*");

        jLabel12.setText("*");

        jLabel14.setText("*");

        jLabel15.setText("Cantidad caja:");

        unidadChk.setText("Es Caja");
        unidadChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadChkActionPerformed(evt);
            }
        });

        cantidadCajaTxt.setText("CANT");

        jLabel2.setText("Producto Relacionado:");

        jLabel16.setText("Código:");

        jLabel17.setText("Filtro:");

        codigoRelacionTxt.setText("CODIGO-RELACION");

        filtroTxt.setText("NOMBRE");

        comboCaja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCajaActionPerformed(evt);
            }
        });

        buscarPorCodigoBtn.setText("Buscar");
        buscarPorCodigoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorCodigoBtnActionPerformed(evt);
            }
        });

        buscarPorFiltroBtn.setText("Buscar");
        buscarPorFiltroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorFiltroBtnActionPerformed(evt);
            }
        });

        jLabel18.setText("Costo sin Iva:");

        costoSinIvaTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        costoSinIvaTxt.setText("COSTO");
        costoSinIvaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                costoSinIvaTxtKeyPressed(evt);
            }
        });

        jLabel19.setText("Margen AYM:");

        margenTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        margenTxt.setText("MARGEN");
        margenTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                margenTxtKeyPressed(evt);
            }
        });

        jLabel20.setText("Costo con Iva:");

        costoConIvaTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        costoConIvaTxt.setText("COSTO CON IVA");
        costoConIvaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                costoConIvaTxtKeyPressed(evt);
            }
        });

        jLabel21.setText("Cantidad por Bulto:");

        cantidadPorBultoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cantidadPorBultoTxt.setText("CAN X Bulto");
        cantidadPorBultoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadPorBultoTxtKeyPressed(evt);
            }
        });

        jLabel22.setText("Descuento:");

        descuentoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        descuentoTxt.setText("dto");
        descuentoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descuentoTxtKeyPressed(evt);
            }
        });

        precioCalculadoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precioCalculadoTxt.setText("PR CALC");

        jLabel23.setText("Precio calculado:");

        jLabel24.setText("Sugerido calculado:");

        sugeridoCalculadoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sugeridoCalculadoTxt.setText("SUG CALC");

        calcularBtn.setText("Calcular");
        calcularBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBtnActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Precio", "Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel25.setText("% iva del producto:");

        comboI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "0", "10.5", "21" }));
        comboI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIActionPerformed(evt);
            }
        });

        jLabel26.setText("Última fecha actualización:");

        ultimaFechaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ultimaFechaTxt.setText("ULTIMA FECHA");

        jLabel27.setText("Margen Cliente:");

        margenClienteTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        margenClienteTxt.setText("MAR CL");
        margenClienteTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                margenClienteTxtKeyPressed(evt);
            }
        });

        jLabel13.setText("Proveedor:");

        nombreProveBuscarTxt.setText("PROVEED");
        nombreProveBuscarTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreProveBuscarTxtKeyPressed(evt);
            }
        });

        comboProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProvActionPerformed(evt);
            }
        });
        comboProv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboProvKeyPressed(evt);
            }
        });

        agregaProveedorBtn.setText("Agrega Proveedor");
        agregaProveedorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregaProveedorBtnActionPerformed(evt);
            }
        });

        idTxt.setText("COD");
        idTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTxtKeyPressed(evt);
            }
        });

        inactivoChk.setText("Inactivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoBarrasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sugeridoCalculadoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(precioTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(precioCalculadoTxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(impuestoTxt)
                                    .addComponent(sugeridoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))))
                        .addGap(152, 152, 152)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboI, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel18)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(costoSinIvaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel21)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cantidadPorBultoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel20)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(costoConIvaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel26)
                                                .addComponent(margenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(unidadChk)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(9, 9, 9)
                                            .addComponent(cantidadCajaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel10))
                                            .addGap(32, 32, 32)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(comboSubRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(comboRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(32, 32, 32))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(filtroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(buscarPorFiltroBtn))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(codigoRelacionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(buscarPorCodigoBtn))
                                        .addComponent(comboCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guardarBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(agregaProveedorBtn)
                                .addGap(120, 120, 120)
                                .addComponent(volerBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ultimaFechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(margenClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(calcularBtn))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreProveBuscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(comboProv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inactivoChk)
                                    .addComponent(descuentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(codigoBarrasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(inactivoChk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(costoSinIvaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(costoConIvaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(descuentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cantidadPorBultoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(margenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(margenClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcularBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(precioCalculadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(ultimaFechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(precioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel25)
                    .addComponent(comboI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(sugeridoCalculadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sugeridoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(impuestoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(comboRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(comboSubRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(unidadChk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cantidadCajaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(codigoRelacionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarPorCodigoBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(filtroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPorFiltroBtn)
                    .addComponent(jLabel13)
                    .addComponent(nombreProveBuscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(volerBtn)
                    .addComponent(agregaProveedorBtn))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volerBtnActionPerformed
        volver();

    }//GEN-LAST:event_volerBtnActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        this.guardar();
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void codigoBarrasTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoBarrasTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoBarrasTxtActionPerformed

    private void comboRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRubroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRubroActionPerformed

    private void unidadChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadChkActionPerformed
        if (unidadChk.isSelected()) {
            cantidadCajaTxt.setEditable(false);
            codigoRelacionTxt.setEditable(false);
            filtroTxt.setEditable(false);
        } else {
            cantidadCajaTxt.setEditable(true);
            codigoRelacionTxt.setEditable(true);
            filtroTxt.setEditable(true);
        }
        cantidadCajaTxt.setText("0");
        comboCaja.removeAllItems();
        comboCaja.addItem("");
    }//GEN-LAST:event_unidadChkActionPerformed

    private void comboCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCajaActionPerformed
        int rows = comboCaja.getItemCount();
        if (rows > 1) {
            mostrar();
        }
    }//GEN-LAST:event_comboCajaActionPerformed

    private void buscarPorCodigoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorCodigoBtnActionPerformed
        buscarPorCodigo();
    }//GEN-LAST:event_buscarPorCodigoBtnActionPerformed

    private void buscarPorFiltroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorFiltroBtnActionPerformed
        buscarPorFiltro();
    }//GEN-LAST:event_buscarPorFiltroBtnActionPerformed

    private void costoSinIvaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoSinIvaTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (costoSinIvaTxt.getText().isEmpty()) {
                costoConIvaTxt.requestFocus();
                return;
            }
            Double precioSinIva = Double.valueOf(costoSinIvaTxt.getText().replace(",", "."));
            Float iva;
            int r = comboI.getSelectedIndex();
            if (r == 0) {
                iva = 0F;
            } else {
                if (r == 1) {
                    iva = 10.5F;
                } else {
                    iva = 21F;
                }
            }
            Double precioConIva = precioSinIva * (1 + iva / 100);
            costoConIvaTxt.setText(df.format(precioConIva));
            costoSinIvaTxt.setText(df.format(precioSinIva));
            descuentoTxt.requestFocus();
        }
    }//GEN-LAST:event_costoSinIvaTxtKeyPressed

    private void costoConIvaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoConIvaTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (costoConIvaTxt.getText().isEmpty()) {
                costoSinIvaTxt.requestFocus();
                return;
            }
            Double precioConIva = Double.valueOf(costoConIvaTxt.getText().replace(",", "."));
            Float iva;
            int r = comboI.getSelectedIndex();
            if (r == 0) {
                iva = 0F;
            } else {
                if (r == 1) {
                    iva = 10.5F;
                } else {
                    iva = 21F;
                }
            }
            Double precioSinIva = precioConIva / (1 + iva / 100);
            costoSinIvaTxt.setText(df.format(precioSinIva));
            costoConIvaTxt.setText(df.format(precioConIva));
            descuentoTxt.requestFocus();
        }
    }//GEN-LAST:event_costoConIvaTxtKeyPressed

    private void margenTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_margenTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (margenTxt.getText().isEmpty()) {
                return;
            }
            margenClienteTxt.requestFocus();
        }
    }//GEN-LAST:event_margenTxtKeyPressed

    private void descuentoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descuentoTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (descuentoTxt.getText().isEmpty()) {
                descuentoTxt.setText("0.0");
            }
            cantidadPorBultoTxt.requestFocus();
        }
    }//GEN-LAST:event_descuentoTxtKeyPressed

    private void cantidadPorBultoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadPorBultoTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (cantidadPorBultoTxt.getText().isEmpty()) {
                cantidadPorBultoTxt.setText("1");
            }
            margenTxt.requestFocus();
        }
    }//GEN-LAST:event_cantidadPorBultoTxtKeyPressed

    private void calcularBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularBtnActionPerformed
        calcular();
    }//GEN-LAST:event_calcularBtnActionPerformed

    private void idTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (idTxt.getText().isEmpty()) {
                idTxt.requestFocus();
                return;
            }
            nombreTxt.requestFocus();
        }
    }//GEN-LAST:event_idTxtKeyPressed

    private void nombreTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (nombreTxt.getText().isEmpty()) {
                return;
            }
            costoSinIvaTxt.requestFocus();
        }
    }//GEN-LAST:event_nombreTxtKeyPressed

    private void margenClienteTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_margenClienteTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (margenClienteTxt.getText().isEmpty()) {
                return;
            }
            calcular();
            precioTxt.requestFocus();
        }
    }//GEN-LAST:event_margenClienteTxtKeyPressed

    private void nombreProveBuscarTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreProveBuscarTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (nombreProveBuscarTxt.getText().isEmpty()) {
                return;
            }
            String f = nombreProveBuscarTxt.getText();
            proveedores = null;
            try {
                proveedores = new ProveedorService().getProveedoresByFiltro(f);
            } catch (Exception ex) {
                Logger.getLogger(ModificarProductoFrame1.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (proveedores != null && !proveedores.isEmpty()) {
                comboProv.removeAllItems();
                comboProv.addItem("");
                for (Proveedor p : proveedores) {
                    comboProv.addItem(p.getCodigo() + " " + p.getRazonSocial());
                }
                comboProv.requestFocus();
                comboProv.addFocusListener(null);
                comboProv.showPopup();
            }
        }
    }//GEN-LAST:event_nombreProveBuscarTxtKeyPressed

    private void comboProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProvActionPerformed
        if (evt.getModifiers() == 16) {
            int r = comboProv.getSelectedIndex();
            if (r > 0) {
                agregaProveedorBtn.requestFocus();
            }
        }
    }//GEN-LAST:event_comboProvActionPerformed

    private void agregaProveedorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregaProveedorBtnActionPerformed
        agregarReferenciaPrecios();
    }//GEN-LAST:event_agregaProveedorBtnActionPerformed

    private void comboIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIActionPerformed
        int r = comboI.getSelectedIndex();
        if (r > 0) {
            Float iva;
            if (r == 1) {
                iva = 0F;
            } else {
                if (r == 2) {
                    iva = 10.5F;
                } else {
                    iva = 21F;
                }
            }
            if (costoSinIvaTxt.getText().isEmpty()) {
                costoSinIvaTxt.requestFocus();
            } else {
                if (costoConIvaTxt.getText().isEmpty()) {
                    costoConIvaTxt.requestFocus();
                } else {
                    //99;
                    Double precioSinIva = Double.valueOf(costoSinIvaTxt.getText().replace(",", "."));
                    Double precioConIva = precioSinIva * (1 + iva / 100);
                    costoSinIvaTxt.setText(df.format(precioSinIva));
                    costoConIvaTxt.setText(df.format(precioConIva));
                    calcular();
                }
            }
        }
    }//GEN-LAST:event_comboIActionPerformed

    private void precioTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (precioTxt.getText().isEmpty()) {
                return;
            }
            sugeridoTxt.requestFocus();
        }
    }//GEN-LAST:event_precioTxtKeyPressed

    private void comboProvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboProvKeyPressed
        if(evt.getKeyCode()==10){
            agregaProveedorBtn.requestFocus();
        }
    }//GEN-LAST:event_comboProvKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProductoFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProductoFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProductoFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProductoFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarProductoFrame1(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregaProveedorBtn;
    private javax.swing.JButton buscarPorCodigoBtn;
    private javax.swing.JButton buscarPorFiltroBtn;
    private javax.swing.JButton calcularBtn;
    private javax.swing.JTextField cantidadCajaTxt;
    private javax.swing.JTextField cantidadPorBultoTxt;
    private javax.swing.JTextField codigoBarrasTxt;
    private javax.swing.JTextField codigoRelacionTxt;
    private javax.swing.JComboBox<String> comboCaja;
    private javax.swing.JComboBox<String> comboI;
    private javax.swing.JComboBox<String> comboProv;
    private javax.swing.JComboBox comboRubro;
    private javax.swing.JComboBox comboSubRubro;
    private javax.swing.JTextField costoConIvaTxt;
    private javax.swing.JTextField costoSinIvaTxt;
    private javax.swing.JTextField descuentoTxt;
    private javax.swing.JTextField filtroTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JTextField idTxt;
    private javax.swing.JTextField impuestoTxt;
    private javax.swing.JCheckBox inactivoChk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField margenClienteTxt;
    private javax.swing.JTextField margenTxt;
    private javax.swing.JTextField nombreProveBuscarTxt;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField precioCalculadoTxt;
    private javax.swing.JTextField precioTxt;
    private javax.swing.JTextField sugeridoCalculadoTxt;
    private javax.swing.JTextField sugeridoTxt;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField ultimaFechaTxt;
    private javax.swing.JCheckBox unidadChk;
    private javax.swing.JButton volerBtn;
    // End of variables declaration//GEN-END:variables

    private void guardar() {
        if (validarCampos()) {
            //Producto producto = new Producto();
            producto.setCodigo(Integer.valueOf(idTxt.getText()));
            producto.setDetalle(nombreTxt.getText());
            if (!codigoBarrasTxt.getText().isEmpty()) {
                producto.setCodigoBarras(Long.valueOf(codigoBarrasTxt.getText()));
            } else {
                producto.setCodigoBarras(null);
            }
            if (!impuestoTxt.getText().isEmpty()) {
                producto.setImpuesto(Float.valueOf(impuestoTxt.getText().replace(",", ".")));
            } else {
                producto.setImpuesto(Float.valueOf("0.00"));
            }
            if (!sugeridoTxt.getText().isEmpty()) {
                producto.setSugerido(Double.valueOf(sugeridoTxt.getText().replace(",", ".")));
            } else {
                producto.setSugerido(Double.valueOf("0.00"));
            }
            producto.setPrecio(Double.valueOf(precioTxt.getText().replace(",", ".")));
            if (inactivoChk.isSelected()) {
                producto.setInactivo(true);
            } else {
                producto.setInactivo(false);
            }
            producto.setStock(0F);
            if (unidadChk.isSelected()) {
                producto.setUnidad(true);
                producto.setCantidadCaja(0);
            } else {
                producto.setUnidad(false);
                int can = Integer.valueOf(cantidadCajaTxt.getText());
                producto.setCantidadCaja(can);
                producto.setProductoCaja(productoRelacionado);
            }
            Double costo = 0.0;
            if (!costoSinIvaTxt.getText().isEmpty()) {
                costo = Double.valueOf(costoSinIvaTxt.getText().replace(",", "."));
            }
            Float margenAyM = 0F;
            if (!margenTxt.getText().isEmpty()) {
                margenAyM = Float.valueOf(margenTxt.getText().replace(",", "."));
            }
            Integer cn = 0;
            if (!cantidadPorBultoTxt.getText().isEmpty()) {
                cn = Integer.valueOf(cantidadPorBultoTxt.getText().replace(",", "."));
            }
            Float dcto = 0F;
            if (!descuentoTxt.getText().isEmpty()) {
                dcto = Float.valueOf(descuentoTxt.getText().replace(",", "."));
            }
            Float margenCli = 0F;
            if (!margenClienteTxt.getText().isEmpty()) {
                margenCli = Float.valueOf(margenClienteTxt.getText().replace(",", "."));
            }
            Date fu = new Date();
            if (!ultimaFechaTxt.getText().isEmpty()) {
                try {
                    fu = sdf.parse(ultimaFechaTxt.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(NuevoProductoFrame1.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "ERROR EN FECHA");
                    ultimaFechaTxt.requestFocus();
                    return;
                }
            }
            producto.setCosto(costo);
            producto.setCantidadPorBulto(cn);
            producto.setDcto(dcto);
            producto.setMargenAyM(margenAyM);
            producto.setMargenCli(margenCli);
            producto.setFechaUltima(fu);
            if (asignarRubro(producto)) {
                if (asignarSubRubro(producto)) {
                    try {
                        producto = new ProductoService().updateProducto(producto);
                        JOptionPane.showMessageDialog(this, "Producto guardado correctamente.");
                        volver();
                    } catch (Exception ex) {
                        //ex.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Ha ocurrido un error "
                                + "guardando el Producto. (Código duplicado)");
                        idTxt.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error (Sub Rubro) guardando el Producto.");
                    comboSubRubro.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error (Rubro) guardando el Producto.");
                comboRubro.requestFocus();
            }
        }
    }

    private void borrarCampos() {
        unidadChk.setSelected(true);
        margenClienteTxt.setText("");
        nombreProveBuscarTxt.setText("");
        comboProv.removeAllItems();
        if (!unidadChk.isSelected()) {
            cantidadCajaTxt.setEditable(false);
            codigoRelacionTxt.setEditable(false);
            filtroTxt.setEditable(false);
        } else {
            cantidadCajaTxt.setEditable(true);
            codigoRelacionTxt.setEditable(true);
            filtroTxt.setEditable(true);
        }
        comboRubro.removeAllItems();
        comboRubro.addItem(" ");
        comboSubRubro.removeAllItems();
        comboSubRubro.addItem(" ");
        comboCaja.removeAllItems();
        comboCaja.addItem("");
        idTxt.setText("");
        codigoBarrasTxt.setText("");
        impuestoTxt.setText("");
        sugeridoTxt.setText("");
        precioTxt.setText("");
        nombreTxt.setText("");
        cantidadCajaTxt.setText("0");
        codigoRelacionTxt.setText("");
        filtroTxt.setText("");
        costoSinIvaTxt.setText("");
        costoConIvaTxt.setText("");
        margenTxt.setText("");
        cantidadPorBultoTxt.setText("");
        precioCalculadoTxt.setText("");
        sugeridoCalculadoTxt.setText("");
        descuentoTxt.setText("");
        ultimaFechaTxt.setText(sdf.format(new Date()));
        comboI.setSelectedIndex(3);
    }

    private void llenarComboRubro() {
        try {
            listaRubros = new RubroService().getAllRubros();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se encuentran Rubros para llenar");
        }
        DefaultComboBoxModel model = (DefaultComboBoxModel) comboRubro.getModel();
        if (listaRubros != null && !listaRubros.isEmpty()) {
            for (Rubro rubro : listaRubros) {
                model.addElement(rubro.getNombre());
            }
            comboRubro.setModel(model);
        }
    }

    private void llenarComboSubRubro() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) comboSubRubro.getModel();
        try {
            listaSubRubros = new SubRubroService().getAllSubRubros();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se encuentran SubRubros para llenar");
        }
        if (listaSubRubros != null && !listaSubRubros.isEmpty()) {
            for (SubRubro subRubro : listaSubRubros) {
                model.addElement(subRubro.getDetalle());
            }
            comboSubRubro.setModel(model);
        }
    }

    private boolean validarCampos() {
        if (nombreTxt.getText().trim().length() > 39) {
            JOptionPane.showMessageDialog(this, "Largo Producto Superado - " + String.valueOf(nombreTxt.getText().trim().length()));
            return false;
        }
        if (idTxt.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Producto - Falta completar CODIGO");
            return false;
        }
        if (nombreTxt.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Producto - Falta completar NOMBRE");
            return false;
        }
        if (precioTxt.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Producto - No permitido Sin precio");
            return false;
        }
        if (comboRubro.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Producto - Seleccione Rubro");
            return false;
        }
        if (comboSubRubro.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "producto - Seleccione Sub Rubro");
            return false;
        }
        if (!unidadChk.isSelected()) {
            if (codigoRelacionTxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "DEBE INDICAR PRODUCTO RELACIONADO");
                codigoRelacionTxt.requestFocus();
                return false;
            }
            if (filtroTxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "DEBE INDICAR PRODUCTO RELACIONADO");
                codigoRelacionTxt.requestFocus();
                return false;
            }
        }
        return true;
    }

    private boolean asignarRubro(Producto prod) {
        int itemSeleccionado = comboRubro.getSelectedIndex();
        if (itemSeleccionado >= 1) {
            prod.setRubro(listaRubros.get(itemSeleccionado - 1));
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Rubro de la lista.");
            return false;
        }
    }

    private boolean asignarSubRubro(Producto prod) {
        int itemSeleccionado = comboSubRubro.getSelectedIndex();
        if (itemSeleccionado >= 1) {
            prod.setSubRubro(listaSubRubros.get(itemSeleccionado - 1));
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un SubRubro de la lista.");
            return false;
        }
    }

    private void mostrar() {
        int row = comboCaja.getSelectedIndex();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN PRODUCTO DE LA LISTA");
            comboCaja.requestFocus();
            return;
        }
        productoRelacionado = null;
        productoRelacionado = productosRelacionados.get(row - 1);
        codigoRelacionTxt.setText(productoRelacionado.getCodigo().toString());
        filtroTxt.setText(productoRelacionado.getDetalle());
        guardarBtn.requestFocus();
    }

    private void buscarPorCodigo() {
        if (codigoRelacionTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "INDIQUE UN CODIGO VALIDO");
            codigoRelacionTxt.requestFocus();
            return;
        }
        int codigo = Integer.valueOf(codigoRelacionTxt.getText());
        productoRelacionado = null;
        try {
            productoRelacionado = new ProductoService().getProductoByCodigo(codigo);
        } catch (Exception ex) {
            Logger.getLogger(ModificarProductoFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (productoRelacionado != null) {
            filtroTxt.setText(productoRelacionado.getDetalle());
            guardarBtn.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "CODIGO INEXISTENTE");
            codigoRelacionTxt.requestFocus();
            return;
        }
    }

    private void buscarPorFiltro() {
        if (filtroTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "INGRESE UN DETALLE A BUSCAR");
            filtroTxt.requestFocus();
            return;
        }
        String filtro2 = filtroTxt.getText();
        productosRelacionados = null;
        try {
            productosRelacionados = new ProductoService().getProductosByFiltroActivosSinDepo(filtro2);
        } catch (Exception ex) {
            Logger.getLogger(ModificarProductoFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        comboCaja.removeAllItems();
        comboCaja.addItem("");
        if (productosRelacionados != null && !productosRelacionados.isEmpty()) {
            for (Producto p : productosRelacionados) {
                comboCaja.addItem(p.getDetalle());
            }
        }
        comboCaja.requestFocus();
        comboCaja.addFocusListener(null);
        comboCaja.showPopup();
    }

    private void calcular() {
        Double ps = Double.valueOf(costoSinIvaTxt.getText().replace(",", "."));
        Double precioSinIva = Double.valueOf(costoSinIvaTxt.getText().replace(",", "."));
        Float iva;
        int r = comboI.getSelectedIndex();
        if (r == 0) {
            iva = 0F;
        } else {
            if (r == 1) {
                iva = 10.5F;
            } else {
                iva = 21F;
            }
        }
        Double precioConIva = precioSinIva * (1 + iva / 100);
        costoConIvaTxt.setText(df.format(precioConIva));
        Float mg = Float.valueOf(margenTxt.getText().replace(",", "."));
        Float mgc = Float.valueOf(margenClienteTxt.getText().replace(",", "."));
        Float dt = Float.valueOf(descuentoTxt.getText().replace(",", "."));
        Integer cn = Integer.valueOf(cantidadPorBultoTxt.getText().replace(",", "."));
        Double tmp0 = ps * dt / 100;
        Double tmp1 = ps - tmp0;
        Double tmp3 = precioConIva * dt / 100;
        Double tmp4 = precioConIva - tmp3;
        Double p_cal = tmp1 * (1 + mg / 100);
        Double pc_cal = tmp4 * (1 + mgc / 100);
        precioCalculadoTxt.setText(df.format(p_cal));
        Double tmp2 = pc_cal / cn;
        sugeridoCalculadoTxt.setText(df.format(tmp2));
    }

    private void agregarReferenciaPrecios() {
        HistorialPrecio hp = new HistorialPrecio();
        Date fu = new Date();
        if (!ultimaFechaTxt.getText().isEmpty()) {
            try {
                fu = sdf.parse(ultimaFechaTxt.getText());
            } catch (ParseException ex) {
                Logger.getLogger(ModificarProductoFrame1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        hp.setFecha(fu);
        hp.setProducto(producto);
        if (costoSinIvaTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe rellenar los campos");
            return;
        }
        Double costo = Double.valueOf(costoSinIvaTxt.getText().replace(",", "."));
        hp.setPrecio(costo);
        int r = comboProv.getSelectedIndex();
        Proveedor p = proveedores.get(r - 1);
        Long ide = p.getId();
        hp.setNombre(ide.toString());
        try {
            new HistorialPrecioService().saveHistorialPrecio(hp);
        } catch (Exception ex) {
            Logger.getLogger(ModificarProductoFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiarTabla();
        llenarTabla();
        return;
    }

    private void llenarCampos() {
        precios = null;
        try {
            precios = new HistorialPrecioService().getByProducto(producto);
        } catch (Exception ex) {
            Logger.getLogger(ModificarProductoFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (precios != null && !precios.isEmpty()) {
            llenarTabla();
        }
        idTxt.setText(producto.getCodigo().toString());
        nombreTxt.setText(producto.getDetalle());
        if (producto.getCodigoBarras() != null) {
            codigoBarrasTxt.setText(producto.getCodigoBarras().toString());
        }
        if (producto.getCosto() != null) {
            costoSinIvaTxt.setText(df.format(producto.getCosto()));
        }
        if (producto.getDcto() != null) {
            descuentoTxt.setText(df1.format(producto.getDcto()));
        }
        if (producto.getCantidadPorBulto() != null) {
            cantidadPorBultoTxt.setText(producto.getCantidadPorBulto().toString());
        }
        if (producto.getMargenAyM() != null) {
            margenTxt.setText(df.format(producto.getMargenAyM()));
        }
        if (producto.getMargenCli() != null) {
            margenClienteTxt.setText(df.format(producto.getMargenCli()));
        }
        if (producto.getFechaUltima() != null) {
            ultimaFechaTxt.setText(sdf.format(producto.getFechaUltima()));
        }
        if (producto.getIvaProducto() != null) {
            comboI.setSelectedIndex(producto.getIvaProducto());
        } else {
            comboI.setSelectedIndex(3);
        }
        if (!costoSinIvaTxt.getText().isEmpty()) {
            calcular();
        }
        precioTxt.setText(df.format(producto.getPrecio()));
        sugeridoTxt.setText(df.format(producto.getSugerido()));
        impuestoTxt.setText(df.format(producto.getImpuesto()));
        if (producto.getInactivo()) {
            inactivoChk.setSelected(true);
        } else {
            inactivoChk.setSelected(false);
        }
        int contador = 0;
        for (Rubro rubro : listaRubros) {
            if (rubro.getId() == producto.getRubro().getId()) {
                break;
            }
            contador++;
        }
        comboRubro.setSelectedIndex(contador + 1);
        contador = 0;
        for (SubRubro sub : listaSubRubros) {
            if (sub.getId() == producto.getSubRubro().getId()) {
                break;
            }
            contador++;
        }
        comboSubRubro.setSelectedIndex(contador + 1);
        if (producto.getUnidad() != null) {
            if (!producto.getUnidad()) {
                unidadChk.setSelected(true);
                cantidadCajaTxt.setText("0");
                cantidadCajaTxt.setEditable(false);
                codigoRelacionTxt.setEditable(false);
                comboCaja.removeAllItems();
                comboCaja.addItem("");
            } else {
                unidadChk.setSelected(false);
                cantidadCajaTxt.setText(producto.getCantidadCaja().toString());
                cantidadCajaTxt.setEditable(true);
                codigoRelacionTxt.setEditable(true);
                if (producto.getProductoCaja() != null) {
                    codigoRelacionTxt.setText(producto.getProductoCaja().getCodigo().toString());
                    int cod = producto.getProductoCaja().getCodigo();
                    try {
                        productoRelacionado = new ProductoService().getProductoByCodigo(cod);
                    } catch (Exception ex) {
                        Logger.getLogger(ModificarProductoFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    filtroTxt.setText(producto.getProductoCaja().getDetalle());
                    comboCaja.removeAllItems();
                    comboCaja.addItem("");
                }
            }
        } else {
            unidadChk.setSelected(true);
            cantidadCajaTxt.setText("0");
            cantidadCajaTxt.setEditable(false);
            codigoRelacionTxt.setEditable(false);
            comboCaja.removeAllItems();
            comboCaja.addItem("");
        }
    }

    private void limpiarTabla() {
        int rows = tabla.getRowCount();
        if (rows > 0) {
            DefaultTableModel tb = (DefaultTableModel) tabla.getModel();
            for (int i = 0; i < rows; i++) {
                tb.removeRow(0);
            }
            tabla.setModel(tb);
        }
    }

    private void llenarTabla() {
        precios = null;
        try {
            precios = new HistorialPrecioService().getByProducto(producto);
        } catch (Exception ex) {
            Logger.getLogger(ModificarProductoFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (precios != null && !precios.isEmpty()) {
            DefaultTableModel tb = (DefaultTableModel) tabla.getModel();
            for (HistorialPrecio h : precios) {
                Object ob[] = new Object[3];
                ob[0] = sdf.format(h.getFecha());
                ob[1] = df.format(h.getPrecio());
                Long cod = Long.valueOf(h.getNombre());
                Proveedor p = null;
                try {
                    p = new ProveedorService().getProveedorById(cod);
                } catch (Exception ex) {
                    Logger.getLogger(ModificarProductoFrame1.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (p != null) {
                    ob[2] = p.getRazonSocial();
                }
                tb.addRow(ob);
            }
            tabla.setModel(tb);
        }
    }

    private void volver() {
        AbmProductoV2Frame abmProductoFrame = new AbmProductoV2Frame(filtro);
        abmProductoFrame.setVisible(true);
        this.dispose();
    }
}
