/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.CtaCteStock;
import ar.com.ventas.entities.Producto;
import ar.com.ventas.entities.Usuario;
import ar.com.ventas.services.CtaCteStockService;
import ar.com.ventas.services.ProductoService;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class ModificarStockFrame extends javax.swing.JFrame {

    private final DecimalFormat df = new DecimalFormat("#0.0");
    private final DecimalFormat dfs = new DecimalFormat("0000");
    private final DecimalFormat dfn = new DecimalFormat("00000000");
    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private final Date de;
    private final Date al;
    private final Integer estado;
    private final Usuario usuario;
    private final List<CtaCteStock> ccs;
    private final CtaCteStock cc1;
    private List<Producto> productos;

    /**
     * Creates new form ModificarStockFrame
     *
     * @param a
     * @param b
     * @param e
     * @param ccs
     * @param u
     * @param cc1
     */
    public ModificarStockFrame(Date a, Date b, Integer e, List<CtaCteStock> ccs, Usuario u, CtaCteStock cc1) {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(245, 222, 179));
        this.de = a;
        this.al = b;
        this.estado = e;
        this.ccs = ccs;
        this.usuario = u;
        this.cc1 = cc1;
        llenarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        volverBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        grabarBtn = new javax.swing.JButton();
        proveedorTxt = new javax.swing.JTextField();
        facturaTxt = new javax.swing.JTextField();
        fechaTxt = new javax.swing.JTextField();
        codigoTxt = new javax.swing.JTextField();
        detalleTxt = new javax.swing.JTextField();
        cantidadTxt = new javax.swing.JTextField();
        filtroTxt = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox<>();
        nuevaCantidadTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        productoCodigoTxt = new javax.swing.JTextField();
        productoDetalleTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MODIFICAR STOCK");

        jLabel1.setText("Proveedor:");

        jLabel2.setText("Factura:");

        jLabel3.setText("Fecha:");

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Código:");

        jLabel5.setText("Detalle:");

        jLabel6.setText("Cantidad:");

        jLabel7.setText("Nuevo Producto:");

        jLabel8.setText("Nueva Cantidad:");

        grabarBtn.setText("Grabar");
        grabarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarBtnActionPerformed(evt);
            }
        });

        proveedorTxt.setText("PROVEEDOR");

        facturaTxt.setText("FACTURA");

        fechaTxt.setText("FECHA");

        codigoTxt.setText("CODIGO");

        detalleTxt.setText("DETALLE");

        cantidadTxt.setText("CANTIDAD");

        filtroTxt.setText("FILTRO");
        filtroTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filtroTxtKeyPressed(evt);
            }
        });

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboKeyPressed(evt);
            }
        });

        nuevaCantidadTxt.setText("NUEVA");
        nuevaCantidadTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nuevaCantidadTxtKeyPressed(evt);
            }
        });

        jLabel9.setText("Producto:");

        productoCodigoTxt.setText("COD PROD");

        productoDetalleTxt.setText("DESCRIPCION PRODUCTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(grabarBtn)
                                    .addComponent(jLabel9))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(facturaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                                .addComponent(fechaTxt)
                                                .addComponent(codigoTxt))
                                            .addComponent(nuevaCantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(detalleTxt)
                                            .addComponent(proveedorTxt)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(filtroTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cantidadTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                                                    .addComponent(productoCodigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(productoDetalleTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                                    .addComponent(combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGap(18, 18, 18)
                                        .addComponent(volverBtn))))))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(volverBtn)
                    .addComponent(proveedorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(facturaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(detalleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(filtroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(productoCodigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productoDetalleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nuevaCantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(grabarBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboKeyPressed
        if (evt.getKeyCode() == 10) {
            cargarP();
        }
    }//GEN-LAST:event_comboKeyPressed

    private void filtroTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            buscarP();
        }
    }//GEN-LAST:event_filtroTxtKeyPressed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        if (evt.getModifiers() == 16) {
            cargarP();
        }
    }//GEN-LAST:event_comboActionPerformed

    private void grabarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarBtnActionPerformed
        //grabar();
    }//GEN-LAST:event_grabarBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void nuevaCantidadTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuevaCantidadTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            grabar();

        }
    }//GEN-LAST:event_nuevaCantidadTxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarStockFrame(null, null, null, null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidadTxt;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField detalleTxt;
    private javax.swing.JTextField facturaTxt;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JTextField filtroTxt;
    private javax.swing.JButton grabarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nuevaCantidadTxt;
    private javax.swing.JTextField productoCodigoTxt;
    private javax.swing.JTextField productoDetalleTxt;
    private javax.swing.JTextField proveedorTxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void llenarCampos() {
        proveedorTxt.setText(cc1.getProveedor().getRazonSocial());
        String f = cc1.getLetra()
                + " " + dfs.format(cc1.getSucursal())
                + "-" + dfn.format(cc1.getNumero());
        facturaTxt.setText(f);
        fechaTxt.setText(sdf.format(cc1.getFecha()));
        codigoTxt.setText(cc1.getProducto().getCodigo().toString());
        detalleTxt.setText(cc1.getProducto().getDetalle());
        cantidadTxt.setText(df.format(cc1.getCantidad()));
        filtroTxt.setText("");
        combo.removeAllItems();
        combo.addItem("");
        productoCodigoTxt.setText("");
        productoDetalleTxt.setText("");
        nuevaCantidadTxt.setText("");
        filtroTxt.requestFocus();
    }

    private void buscarP() {
        String filtro = filtroTxt.getText();
        if (filtro.isEmpty()) {
            return;
        }
        productos = null;
        try {
            productos = new ProductoService().getProductosByFiltro(filtro);
        } catch (Exception ex) {
            Logger.getLogger(ModificarStockFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (productos != null && !productos.isEmpty()) {
            for (Producto pr : productos) {
                combo.addItem(pr.getDetalle());
            }
            combo.addFocusListener(null);
            combo.showPopup();
            combo.requestFocus();
        }
    }

    private void cargarP() {
        int row = combo.getSelectedIndex();
        if (row < 1) {
            return;
        }
        Producto pro = productos.get(row - 1);
        productoCodigoTxt.setText(pro.getCodigo().toString());
        productoDetalleTxt.setText(pro.getDetalle());
        nuevaCantidadTxt.requestFocus();
    }

    private void grabar() {
        int a = JOptionPane.showConfirmDialog(this, "CONFIRMA GRABAR LA MODIFICACION?", "Atención", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            if (!nuevaCantidadTxt.getText().isEmpty()) {
                int row = combo.getSelectedIndex();
                if (row < 1) {
                    return;
                }
                Producto pro = productos.get(row - 1);
                Float cantNew = Float.valueOf(nuevaCantidadTxt.getText());
                CtaCteStock cc2 = new CtaCteStock();
                cc2.setCantidad(cantNew);
                cc2.setComprobante(cc1.getComprobante());
                cc2.setFecha(new Date());
                cc2.setLetra(cc1.getLetra());
                cc2.setNumero(cc1.getNumero());
                cc2.setProducto(pro);
                cc2.setProveedor(cc1.getProveedor());
                cc2.setSucursal(cc1.getSucursal());
                cc2.setUsuario(usuario);
                Integer codi = pro.getCodigo();
                Producto prod = null;
                try {
                    prod = new ProductoService().getProductoByCodigo(codi);
                } catch (Exception ex) {
                    Logger.getLogger(ModificarStockFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                Float ne = prod.getStock() + cantNew;
                prod.setStock(ne);
                try {
                    new ProductoService().updateProducto(prod);
                } catch (Exception ex) {
                    Logger.getLogger(ModificarStockFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                codi = cc1.getProducto().getCodigo();
                prod = null;
                try {
                    prod = new ProductoService().getProductoByCodigo(codi);
                } catch (Exception ex) {
                    Logger.getLogger(ModificarStockFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                ne = prod.getStock() - cc1.getCantidad();
                prod.setStock(ne);
                try {
                    new ProductoService().updateProducto(prod);
                } catch (Exception ex) {
                    Logger.getLogger(ModificarStockFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    new CtaCteStockService().saveCtaCteStock(cc2);
                } catch (Exception ex) {
                    Logger.getLogger(ModificarStockFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    private void volver() {
        CuentaCorrienteStockFrame ccsf = new CuentaCorrienteStockFrame(de, al, estado, ccs, usuario);
        ccsf.setVisible(true);
        this.dispose();
    }
}
