/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Proveedor;
import ar.com.ventas.services.ProveedorService;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class ModificarProveedorFrame extends javax.swing.JFrame {

    private Proveedor proveedor = null;

    /**
     * Creates new form ModificarProveedorFrame
     */
    public ModificarProveedorFrame(Proveedor prove) {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(245, 222, 179));
        this.proveedor = prove;
        this.llenarCampo(prove);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        codigoTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        cuitTxt = new javax.swing.JTextField();
        telTxt = new javax.swing.JTextField();
        celularTxt = new javax.swing.JTextField();
        mailTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        guardarBtn = new javax.swing.JButton();
        vovlerBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        obsTxt = new javax.swing.JTextArea();
        comboCategoria = new javax.swing.JComboBox();
        activoChk = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        contactoTxt = new javax.swing.JTextField();
        llevaStockChk = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MODIFICAR PROVEEDOR");

        jLabel1.setText("Código");

        jLabel2.setText("Razón Social");

        jLabel3.setText("Categoría iva");

        jLabel8.setText("Teléfono");

        jLabel9.setText("Mail");

        jLabel13.setText("Cuit");

        jLabel14.setText("Celular");

        codigoTxt.setText("id");
        codigoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoTxtKeyPressed(evt);
            }
        });

        nombreTxt.setText("Nombre");

        cuitTxt.setText("Cuit");

        telTxt.setText("Telefono");
        telTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telTxtActionPerformed(evt);
            }
        });

        celularTxt.setText("Celular");

        mailTxt.setText("Mail");

        jLabel15.setText("Observaciones");

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        vovlerBtn.setText("Volver");
        vovlerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vovlerBtnActionPerformed(evt);
            }
        });

        obsTxt.setColumns(20);
        obsTxt.setRows(5);
        jScrollPane1.setViewportView(obsTxt);

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        activoChk.setText("Activo");

        jLabel4.setText("Contacto:");

        contactoTxt.setText("CONTACTO");

        llevaStockChk.setText("Lleva Stock");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(guardarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vovlerBtn)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(telTxt)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14))
                                    .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(activoChk))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(llevaStockChk)
                                    .addComponent(celularTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(144, 144, 144))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreTxt)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cuitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(contactoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(llevaStockChk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14)
                    .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celularTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activoChk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(contactoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(vovlerBtn))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telTxtActionPerformed

    private void vovlerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vovlerBtnActionPerformed
        AbmProveedoresFrame apf = new AbmProveedoresFrame();
        apf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vovlerBtnActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        this.guardar();
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void codigoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTxtKeyPressed

    }//GEN-LAST:event_codigoTxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProveedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProveedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProveedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProveedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarProveedorFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activoChk;
    private javax.swing.JTextField celularTxt;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JComboBox comboCategoria;
    private javax.swing.JTextField contactoTxt;
    private javax.swing.JTextField cuitTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox llevaStockChk;
    private javax.swing.JTextField mailTxt;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextArea obsTxt;
    private javax.swing.JTextField telTxt;
    private javax.swing.JButton vovlerBtn;
    // End of variables declaration//GEN-END:variables

    private void guardar() {
        if (validarCampos()) {
            //Domicilio domicilio = proveedor.getDomicilio();
//            domicilio.setDepartamento(departamentoTxt.getText());
//            domicilio.setCalle(calleTxt.getText());
//            domicilio.setCodigoPostal(cpTxt.getText());
//            domicilio.setNumero(numeroTxt.getText());
//            domicilio.setLocalidad(localidadTxt.getText());
//            domicilio.setProvincia(provinciaTxt.getText());
//            domicilio.setDepartamento(departamentoTxt.getText());
//            proveedor.setCodigo(Integer.valueOf(codigoTxt.getText()));
            proveedor.setRazonSocial(nombreTxt.getText());
//            proveedor.setCuit(cuitTxt.getText());
            proveedor.setTelefono(telTxt.getText());
            proveedor.setCelular(celularTxt.getText());
            proveedor.setMail(mailTxt.getText());
            proveedor.setContacto(contactoTxt.getText());
            proveedor.setObservaciones(obsTxt.getText());
            //proveedor.setDomicilio(domicilio);
            proveedor.setCategoriaIva(comboCategoria.getSelectedIndex());
            if (activoChk.isSelected()) {
                proveedor.setActivo(true);
            } else {
                proveedor.setActivo(false);
            }
            if (llevaStockChk.isSelected()) {
                proveedor.setStock(true);
            } else {
                proveedor.setStock(false);
            }
            try {
                new ProveedorService().updateProveedor(proveedor);
                JOptionPane.showMessageDialog(this, "Proveedor - Guardado correctamente");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Proveedor - No se puede guardar el proveedor");
            }
            AbmProveedoresFrame apf = new AbmProveedoresFrame();
            apf.setVisible(true);
            this.dispose();
        }
    }

    private void llenarCampo(Proveedor prove) {
        //Domicilio domicilio = prove.getDomicilio();
        codigoTxt.setText(String.valueOf(prove.getCodigo()));
        nombreTxt.setText(prove.getRazonSocial());
//        calleTxt.setText(domicilio.getCalle());
//        numeroTxt.setText(domicilio.getNumero());
//        departamentoTxt.setText(domicilio.getDepartamento());
//        cpTxt.setText(domicilio.getCodigoPostal());
//        localidadTxt.setText(domicilio.getLocalidad());
//        provinciaTxt.setText(domicilio.getProvincia());
        cuitTxt.setText(prove.getCuit());
        telTxt.setText(prove.getTelefono());
        celularTxt.setText(prove.getCelular());
        mailTxt.setText(prove.getMail());
        obsTxt.setText(prove.getObservaciones());
        if (prove.getStock() != null) {
            if (prove.getStock()) {
                llevaStockChk.setSelected(true);
            } else {
                llevaStockChk.setSelected(false);
            }
        }else{
            llevaStockChk.setSelected(true);
        }
        if (prove.getContacto() != null) {
            contactoTxt.setText(prove.getContacto());
        } else {
            contactoTxt.setText("");
        }
        if (prove.getActivo()) {
            activoChk.setSelected(true);
        } else {
            activoChk.setSelected(false);
        }
        codigoTxt.setEditable(false);
        DefaultComboBoxModel model = (DefaultComboBoxModel) comboCategoria.getModel();
        model.removeAllElements();
        model.addElement("");
        model.addElement("1- Inscripto");
        model.addElement("2- Monotributo");
        model.addElement("3- Exento");
        model.addElement("4- Consumidor Final");

        comboCategoria.setModel(model);

        if (proveedor.getCategoriaIva() != null) {
            comboCategoria.setSelectedIndex(proveedor.getCategoriaIva());
        }
    }

    public boolean validarCampos() {
        if (nombreTxt.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Proveedor - Falta completar la razon social");
            return false;
        }
        if (codigoTxt.getText().trim().length() == 0) {
            JOptionPane.showConfirmDialog(this, "Proveedor - Falta completar el codigo");
            return false;
        }
        if (comboCategoria.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Proveedor - Seleccione categoría de iva");
            return false;
        }
//        if(calleTxt.getText().trim().length()==0){
//            JOptionPane.showMessageDialog(this, "Proveedor - Falta completar nombre de la calle");
//            return false;
//        }
//        if(numeroTxt.getText().trim().length()==0){
//            JOptionPane.showMessageDialog(this, "Proveedor - Falta completar numero de la direccion");
//            return false;
//        }
        if (cuitTxt.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Proveedor - Falta completar cuit ");
            return false;
        }
        return true;
    }

    private boolean verificarDuplicado() {
        Boolean libre = true;
        if (!codigoTxt.getText().isEmpty()) {
            int cod = Integer.valueOf(codigoTxt.getText());
            Proveedor p = null;
            try {
                p = new ProveedorService().getProveedorByCodigo(cod);
                if (p != null) {
                    libre = false;
                }
            } catch (Exception ex) {
                Logger.getLogger(ModificarProveedorFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (libre) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Número Proveedor existente");
            return false;
        }
    }

}
